# Generated by Django 3.0.4 on 2020-03-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashcardSet',
            new_name='Deck',
        ),
    ]
