# Generated by Django 3.0.4 on 2020-03-26 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story_cards', '0003_auto_20200326_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
