# Generated by Django 3.0.4 on 2020-03-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_cards', '0005_deck_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
