# Generated by Django 3.0.4 on 2020-03-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_cards', '0006_auto_20200326_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='flashcards',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ManyToManyField(to='story_cards.Deck'),
        ),
    ]
