# Generated by Django 3.0.4 on 2020-04-01 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_cards', '0007_auto_20200328_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='team',
        ),
        migrations.AddField(
            model_name='deck',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='story_cards.Team'),
        ),
    ]
