# Generated by Django 3.0.4 on 2020-04-01 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_cards', '0008_auto_20200401_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_cards.Team'),
        ),
    ]
