# Generated by Django 3.0.4 on 2020-04-01 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_cards', '0009_auto_20200401_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='deck',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='story_cards.Deck'),
        ),
    ]
