# Generated by Django 3.0.4 on 2020-04-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_cards', '0011_auto_20200401_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='antonym',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='example_usage',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='picture',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='synonym',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
