# Generated by Django 3.0.4 on 2020-04-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_cards', '0012_auto_20200404_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='synonym',
            new_name='hint',
        ),
    ]
